#!/usr/bin/env Rscript

###############################################################################
# GeoMx DSP SpatialDecon analysis and Figure 1G
#
# Study:
#   Obesity-associated colorectal cancer spatial transcriptomics
#
# Purpose:
#   1. Load the Q3-normalized GeoMx object generated by
#      01_preprocessing_QC_normalization.R.
#   2. Run SpatialDecon using the safeTME reference matrix used in the study.
#   3. Extract cell-type abundance estimates.
#   4. Reproduce Figure 1G for immune (CD3) ROIs:
#        - ROI-level stacked cell-composition bars
#        - Group-level pie charts for
#            Normal / Non-obese
#            Normal / Obese
#            Tumor  / Non-obese
#            Tumor  / Obese
#
# Inputs:
#   results/GeoMx/01_preprocessing_QC_normalization/
#     GeoMx_preprocessed_Q3_normalized.rds
#
#   data/GeoMx/SpatialDecon/
#     safeTME-for-tumor-immune.csv
#
# Outputs:
#   results/GeoMx/04_spatialdecon/
#
###############################################################################


###############################################################################
# 0. Configuration
###############################################################################

PREPROCESSED_RDS <- Sys.getenv(
  "GEOMX_PREPROCESSED_RDS",
  unset = file.path(
    "results",
    "GeoMx",
    "01_preprocessing_QC_normalization",
    "GeoMx_preprocessed_Q3_normalized.rds"
  )
)

SAFETME_FILE <- Sys.getenv(
  "GEOMX_SAFETME_FILE",
  unset = file.path(
    "data",
    "GeoMx",
    "SpatialDecon",
    "safeTME-for-tumor-immune.csv"
  )
)

OUTPUT_DIR <- Sys.getenv(
  "GEOMX_SPATIALDECON_OUTPUT_DIR",
  unset = file.path(
    "results",
    "GeoMx",
    "04_spatialdecon"
  )
)

dir.create(
  OUTPUT_DIR,
  recursive = TRUE,
  showWarnings = FALSE
)


###############################################################################
# 1. Required packages
###############################################################################

required_packages <- c(
  "Biobase",
  "GeomxTools",
  "SpatialDecon",
  "dplyr",
  "tidyr",
  "tibble",
  "ggplot2",
  "patchwork"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    logical(1),
    quietly = TRUE
  )
]

if (length(missing_packages) > 0) {
  stop(
    "Missing required package(s): ",
    paste(missing_packages, collapse = ", ")
  )
}

suppressPackageStartupMessages({
  library(Biobase)
  library(GeomxTools)
  library(SpatialDecon)
  library(dplyr)
  library(tidyr)
  library(tibble)
  library(ggplot2)
  library(patchwork)
})


###############################################################################
# 2. Helper functions
###############################################################################

clean_sample_id <- function(x) {

  x <- basename(as.character(x))

  x <- sub(
    "\\.dcc$",
    "",
    x,
    ignore.case = TRUE
  )

  x
}


standardize_class <- function(x) {

  x <- trimws(as.character(x))

  dplyr::case_when(
    tolower(x) == "normal" ~ "Normal",
    tolower(x) %in% c("tumor", "tumour") ~ "Tumor",
    TRUE ~ x
  )
}


standardize_obesity <- function(x) {

  x <- trimws(as.character(x))
  low <- tolower(x)

  dplyr::case_when(
    low %in% c(
      "normal",
      "non-obese",
      "nonobese",
      "non obese",
      "non_obese"
    ) ~ "Normal",

    low == "obese" ~ "Obese",

    TRUE ~ x
  )
}


standardize_roi_type <- function(x) {

  x <- trimws(as.character(x))

  dplyr::case_when(
    tolower(x) %in% c(
      "cd3",
      "immune",
      "immune cell"
    ) ~ "CD3",

    tolower(x) %in% c(
      "adipose",
      "adipose tissue"
    ) ~ "Adipose",

    tolower(x) %in% c(
      "epithelial",
      "epithelium",
      "colon",
      "tumor",
      "tumour"
    ) ~ "Epithelial",

    TRUE ~ x
  )
}


###############################################################################
# 3. Load preprocessed GeoMx object
###############################################################################

if (!file.exists(PREPROCESSED_RDS)) {
  stop(
    "Preprocessed GeoMx object was not found:\n",
    PREPROCESSED_RDS,
    "\nRun 01_preprocessing_QC_normalization.R first."
  )
}

target_geomx <- readRDS(
  PREPROCESSED_RDS
)

if (!"q_norm" %in% Biobase::assayDataElementNames(target_geomx)) {
  stop(
    "The input GeoMx object does not contain the 'q_norm' assay element."
  )
}

if (!"exprs" %in% Biobase::assayDataElementNames(target_geomx)) {
  stop(
    "The input GeoMx object does not contain the raw 'exprs' assay element."
  )
}

metadata <- as.data.frame(
  Biobase::pData(target_geomx),
  check.names = FALSE
)

message(
  "Loaded GeoMx object: ",
  nrow(target_geomx),
  " targets x ",
  ncol(target_geomx),
  " ROIs"
)


###############################################################################
# 4. Resolve metadata columns
###############################################################################

# ROI type
if ("ROIType" %in% colnames(metadata)) {

  metadata$ROIType_final <- standardize_roi_type(
    metadata$ROIType
  )

} else if ("segment" %in% colnames(metadata)) {

  metadata$ROIType_final <- standardize_roi_type(
    metadata$segment
  )

} else {

  stop(
    "Neither 'ROIType' nor 'segment' was found in GeoMx metadata."
  )
}


# Normal vs Tumor
if (!"class" %in% colnames(metadata)) {
  stop(
    "The 'class' metadata column is required for Figure 1G."
  )
}

metadata$Class_final <- standardize_class(
  metadata$class
)


# Obesity
if ("CategoryTwo" %in% colnames(metadata)) {

  metadata$Obesity_final <- standardize_obesity(
    metadata$CategoryTwo
  )

} else if ("Category" %in% colnames(metadata)) {

  metadata$Obesity_final <- standardize_obesity(
    metadata$Category
  )

} else {

  stop(
    "Neither 'CategoryTwo' nor 'Category' was found in GeoMx metadata."
  )
}


# Nuclei counts
nuclei_candidates <- c(
  "nuclei",
  "Nuclei",
  "Nuclei.Count",
  "nuclei_count"
)

nuclei_col <- nuclei_candidates[
  nuclei_candidates %in% colnames(metadata)
][1]

if (is.na(nuclei_col)) {
  stop(
    "A nuclei-count metadata column was not found. ",
    "The original SpatialDecon workflow supplied nuclei counts through ",
    "cell_counts."
  )
}

metadata$Nuclei_final <- as.numeric(
  metadata[[nuclei_col]]
)


# Keep a de-identified ROI ID
metadata$ROI <- clean_sample_id(
  rownames(metadata)
)

rownames(metadata) <- metadata$ROI


###############################################################################
# 5. Load safeTME reference matrix
###############################################################################

if (!file.exists(SAFETME_FILE)) {
  stop(
    "safeTME reference matrix was not found:\n",
    SAFETME_FILE,
    "\nSet GEOMX_SAFETME_FILE to the location of ",
    "safeTME-for-tumor-immune.csv."
  )
}

profile_df <- read.csv(
  SAFETME_FILE,
  header = TRUE,
  check.names = FALSE,
  stringsAsFactors = FALSE
)

if (ncol(profile_df) < 2) {
  stop(
    "safeTME reference file must contain a gene column and ",
    "one or more cell-type columns."
  )
}

gene_ids <- as.character(
  profile_df[[1]]
)

profile_matrix <- as.matrix(
  profile_df[, -1, drop = FALSE]
)

storage.mode(profile_matrix) <- "numeric"

rownames(profile_matrix) <- gene_ids

if (anyDuplicated(rownames(profile_matrix))) {
  stop(
    "Duplicate gene names were found in the safeTME reference matrix."
  )
}

message(
  "Loaded safeTME reference: ",
  nrow(profile_matrix),
  " genes x ",
  ncol(profile_matrix),
  " cell types"
)


###############################################################################
# 6. Run SpatialDecon
###############################################################################

# The recovered study scripts used:
#
#   norm_elt   = "q_norm"
#   raw_elt    = "exprs"
#   X          = safeTME profile matrix
#   cell_counts = nuclei
#
# The background calculation below is retained as a QC/export step because it
# was also present in the original workflow.

background <- SpatialDecon::derive_GeoMx_background(
  norm = Biobase::assayDataElement(
    target_geomx,
    elt = "q_norm"
  ),
  probepool = Biobase::fData(target_geomx)$Module,
  negnames = "NegProbe-WTX"
)

saveRDS(
  background,
  file.path(
    OUTPUT_DIR,
    "GeoMx_SpatialDecon_background.rds"
  )
)

res <- SpatialDecon::runspatialdecon(
  target_geomx,
  norm_elt = "q_norm",
  raw_elt = "exprs",
  X = profile_matrix,
  cell_counts = metadata$Nuclei_final
)

saveRDS(
  res,
  file.path(
    OUTPUT_DIR,
    "GeoMx_SpatialDecon_result.rds"
  )
)


###############################################################################
# 7. Extract cell abundance matrix
###############################################################################

cell_counts_matrix <- res$cell.counts$cell.counts

if (is.null(cell_counts_matrix)) {
  stop(
    "SpatialDecon result did not contain res$cell.counts$cell.counts."
  )
}

cell_counts_matrix <- as.matrix(
  cell_counts_matrix
)

storage.mode(cell_counts_matrix) <- "numeric"

# Expected orientation in the original workflow:
# rows = ROIs, columns = cell types.
if (nrow(cell_counts_matrix) != nrow(metadata) &&
    ncol(cell_counts_matrix) == nrow(metadata)) {

  cell_counts_matrix <- t(
    cell_counts_matrix
  )
}

if (nrow(cell_counts_matrix) != nrow(metadata)) {
  stop(
    "SpatialDecon cell-count matrix could not be aligned to GeoMx ROIs. ",
    "Cell-count matrix dimensions: ",
    paste(dim(cell_counts_matrix), collapse = " x "),
    "; metadata ROIs: ",
    nrow(metadata)
  )
}


# Align ROI names.
if (!is.null(rownames(cell_counts_matrix))) {

  cc_ids <- clean_sample_id(
    rownames(cell_counts_matrix)
  )

  md_ids <- rownames(metadata)

  if (all(cc_ids %in% md_ids)) {

    rownames(cell_counts_matrix) <- cc_ids

    metadata <- metadata[
      rownames(cell_counts_matrix),
      ,
      drop = FALSE
    ]

  } else {

    warning(
      "SpatialDecon output ROI names could not be matched directly to ",
      "metadata. Row order will be used."
    )

    rownames(cell_counts_matrix) <- metadata$ROI
  }

} else {

  rownames(cell_counts_matrix) <- metadata$ROI
}


write.csv(
  data.frame(
    ROI = rownames(cell_counts_matrix),
    cell_counts_matrix,
    check.names = FALSE
  ),
  file.path(
    OUTPUT_DIR,
    "GeoMx_SpatialDecon_cell_abundance.csv"
  ),
  row.names = FALSE
)


###############################################################################
# 8. Convert SpatialDecon result to long format
###############################################################################

cell_long <- as.data.frame(
  cell_counts_matrix,
  check.names = FALSE
) |>
  tibble::rownames_to_column(
    "ROI"
  ) |>
  tidyr::pivot_longer(
    cols = -ROI,
    names_to = "CellType",
    values_to = "Abundance"
  ) |>
  dplyr::left_join(
    metadata |>
      tibble::rownames_to_column(
        "ROI_join"
      ) |>
      dplyr::transmute(
        ROI = ROI_join,
        ROIType = ROIType_final,
        Class = Class_final,
        Obesity = Obesity_final,
        Nuclei = Nuclei_final
      ),
    by = "ROI"
  )


# Match the original workflow: remove cell types with zero abundance over all
# ROIs.
nonzero_celltypes <- cell_long |>
  dplyr::group_by(CellType) |>
  dplyr::summarise(
    TotalAbundance = sum(
      Abundance,
      na.rm = TRUE
    ),
    .groups = "drop"
  ) |>
  dplyr::filter(
    TotalAbundance != 0
  ) |>
  dplyr::pull(CellType)

cell_long <- cell_long |>
  dplyr::filter(
    CellType %in% nonzero_celltypes
  )


###############################################################################
# 9. Convert abundance to ROI-level proportions
###############################################################################

cell_prop_long <- cell_long |>
  dplyr::group_by(ROI) |>
  dplyr::mutate(
    TotalAbundance = sum(
      Abundance,
      na.rm = TRUE
    ),
    Proportion = dplyr::if_else(
      TotalAbundance > 0,
      Abundance / TotalAbundance,
      NA_real_
    )
  ) |>
  dplyr::ungroup()


write.csv(
  cell_long,
  file.path(
    OUTPUT_DIR,
    "GeoMx_SpatialDecon_cell_abundance_long.csv"
  ),
  row.names = FALSE
)

write.csv(
  cell_prop_long,
  file.path(
    OUTPUT_DIR,
    "GeoMx_SpatialDecon_cell_proportions_long.csv"
  ),
  row.names = FALSE
)


###############################################################################
# 10. Figure 1G data: immune (CD3) ROIs only
###############################################################################

fig1g_data <- cell_prop_long |>
  dplyr::filter(
    ROIType == "CD3"
  ) |>
  dplyr::mutate(
    Group = dplyr::case_when(
      Class == "Normal" & Obesity == "Normal" ~ "Normal - Non Obese",
      Class == "Normal" & Obesity == "Obese"  ~ "Normal - Obese",
      Class == "Tumor"  & Obesity == "Normal" ~ "Tumor - Non Obese",
      Class == "Tumor"  & Obesity == "Obese"  ~ "Tumor - Obese",
      TRUE ~ NA_character_
    )
  ) |>
  dplyr::filter(
    !is.na(Group)
  )

group_levels <- c(
  "Normal - Non Obese",
  "Normal - Obese",
  "Tumor - Non Obese",
  "Tumor - Obese"
)

fig1g_data$Group <- factor(
  fig1g_data$Group,
  levels = group_levels
)


if (nrow(fig1g_data) == 0) {
  stop(
    "No CD3/immune ROIs were found after metadata standardization."
  )
}


###############################################################################
# 11. Preserve original Figure 1G cell-type colors
###############################################################################

celltype_colors <- c(
  "T.CD4.memory" = "pink",
  "T.CD4.naive" = "salmon",
  "Treg" = "red",

  "T.CD8.memory" = "darkgoldenrod1",
  "T.CD8.naive" = "darkorange",

  "B.memory" = "steelblue",
  "B.naive" = "deepskyblue",
  "plasma" = "cyan",

  "NK" = "mediumpurple",

  "macrophages" = "seagreen",
  "monocytes.NC.I" = "forestgreen",
  "monocytes.C" = "aquamarine",
  "mDCs" = "azure",
  "pDCs" = "darkolivegreen",
  "neutrophils" = "yellowgreen",
  "mast" = "chartreuse",

  "fibroblasts" = "grey50",
  "endothelial.cells" = "saddlebrown"
)


# Any unexpected cell type is assigned an automatic fallback color.
missing_colors <- setdiff(
  unique(fig1g_data$CellType),
  names(celltype_colors)
)

if (length(missing_colors) > 0) {

  fallback_colors <- scales::hue_pal()(
    length(missing_colors)
  )

  names(fallback_colors) <- missing_colors

  celltype_colors <- c(
    celltype_colors,
    fallback_colors
  )
}

celltype_colors <- celltype_colors[
  unique(fig1g_data$CellType)
]


###############################################################################
# 12. Figure 1G-left: ROI-level stacked composition bars
###############################################################################

# Keep ROIs grouped as:
# Normal/non-obese -> Normal/obese -> Tumor/non-obese -> Tumor/obese.
roi_order <- fig1g_data |>
  dplyr::distinct(
    ROI,
    Group
  ) |>
  dplyr::arrange(
    Group,
    ROI
  ) |>
  dplyr::pull(
    ROI
  )

fig1g_data$ROI_plot <- factor(
  fig1g_data$ROI,
  levels = roi_order
)

fig1g_bar <- ggplot(
  fig1g_data,
  aes(
    x = ROI_plot,
    y = Proportion,
    fill = CellType
  )
) +
  geom_col(
    width = 1
  ) +
  facet_grid(
    . ~ Group,
    scales = "free_x",
    space = "free_x"
  ) +
  scale_fill_manual(
    values = celltype_colors,
    name = "Cell Type"
  ) +
  scale_y_continuous(
    limits = c(0, 1),
    expand = c(0, 0)
  ) +
  labs(
    x = NULL,
    y = "Proportion"
  ) +
  theme_classic(
    base_size = 11
  ) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(
      size = 10,
      face = "bold"
    ),
    panel.spacing.x = grid::unit(
      1.5,
      "mm"
    ),
    legend.position = "right"
  )

print(fig1g_bar)

ggsave(
  file.path(
    OUTPUT_DIR,
    "Figure1G_CD3_stacked_bar.pdf"
  ),
  plot = fig1g_bar,
  width = 11,
  height = 5.5,
  units = "in"
)

ggsave(
  file.path(
    OUTPUT_DIR,
    "Figure1G_CD3_stacked_bar.png"
  ),
  plot = fig1g_bar,
  width = 11,
  height = 5.5,
  units = "in",
  dpi = 600
)


###############################################################################
# 13. Figure 1G-right: group-level pie charts
###############################################################################

# The original Figure 1G workflow summed SpatialDecon abundance values within
# each clinical group and cell type, then normalized each group to 100%.
pie_data <- cell_long |>
  dplyr::filter(
    ROIType == "CD3"
  ) |>
  dplyr::mutate(
    Group = dplyr::case_when(
      Class == "Normal" & Obesity == "Normal" ~ "Normal - Non Obese",
      Class == "Normal" & Obesity == "Obese"  ~ "Normal - Obese",
      Class == "Tumor"  & Obesity == "Normal" ~ "Tumor - Non Obese",
      Class == "Tumor"  & Obesity == "Obese"  ~ "Tumor - Obese",
      TRUE ~ NA_character_
    )
  ) |>
  dplyr::filter(
    !is.na(Group)
  ) |>
  dplyr::group_by(
    Group,
    CellType
  ) |>
  dplyr::summarise(
    Abundance = sum(
      Abundance,
      na.rm = TRUE
    ),
    .groups = "drop"
  ) |>
  dplyr::group_by(
    Group
  ) |>
  dplyr::mutate(
    Percent = Abundance /
      sum(
        Abundance,
        na.rm = TRUE
      ) * 100
  ) |>
  dplyr::ungroup()

pie_data$Group <- factor(
  pie_data$Group,
  levels = group_levels
)

write.csv(
  pie_data,
  file.path(
    OUTPUT_DIR,
    "Figure1G_group_composition.csv"
  ),
  row.names = FALSE
)

fig1g_pie <- ggplot(
  pie_data,
  aes(
    x = "",
    y = Percent,
    fill = CellType
  )
) +
  geom_col(
    width = 1,
    color = "black",
    linewidth = 0.15
  ) +
  coord_polar(
    theta = "y"
  ) +
  facet_wrap(
    ~ Group,
    ncol = 2
  ) +
  scale_fill_manual(
    values = celltype_colors,
    name = "Cell Type"
  ) +
  theme_void(
    base_size = 11
  ) +
  theme(
    strip.text = element_text(
      size = 10,
      face = "bold"
    ),
    legend.position = "right"
  )

print(fig1g_pie)

ggsave(
  file.path(
    OUTPUT_DIR,
    "Figure1G_CD3_group_piecharts.pdf"
  ),
  plot = fig1g_pie,
  width = 8.5,
  height = 6.5,
  units = "in"
)

ggsave(
  file.path(
    OUTPUT_DIR,
    "Figure1G_CD3_group_piecharts.png"
  ),
  plot = fig1g_pie,
  width = 8.5,
  height = 6.5,
  units = "in",
  dpi = 600
)


###############################################################################
# 14. Combined Figure 1G
###############################################################################

fig1g_combined <- fig1g_bar +
  fig1g_pie +
  patchwork::plot_layout(
    widths = c(1.8, 1)
  ) +
  patchwork::plot_annotation(
    title = "Immune Cell Composition"
  )

print(fig1g_combined)

ggsave(
  file.path(
    OUTPUT_DIR,
    "Figure1G_SpatialDecon_combined.pdf"
  ),
  plot = fig1g_combined,
  width = 16,
  height = 6.5,
  units = "in"
)

ggsave(
  file.path(
    OUTPUT_DIR,
    "Figure1G_SpatialDecon_combined.png"
  ),
  plot = fig1g_combined,
  width = 16,
  height = 6.5,
  units = "in",
  dpi = 600
)


###############################################################################
# 15. Figure 1G sample counts
###############################################################################

fig1g_roi_counts <- fig1g_data |>
  dplyr::distinct(
    ROI,
    Group
  ) |>
  dplyr::count(
    Group,
    name = "N_ROIs"
  )

write.csv(
  fig1g_roi_counts,
  file.path(
    OUTPUT_DIR,
    "Figure1G_CD3_ROI_counts.csv"
  ),
  row.names = FALSE
)


###############################################################################
# 16. Save analysis summary and software versions
###############################################################################

summary_lines <- c(
  paste0(
    "Input GeoMx object: ",
    PREPROCESSED_RDS
  ),
  paste0(
    "safeTME reference: ",
    SAFETME_FILE
  ),
  paste0(
    "GeoMx ROIs deconvolved: ",
    nrow(cell_counts_matrix)
  ),
  paste0(
    "SpatialDecon cell types retained: ",
    length(unique(cell_long$CellType))
  ),
  paste0(
    "CD3/immune ROIs used in Figure 1G: ",
    dplyr::n_distinct(fig1g_data$ROI)
  ),
  "SpatialDecon normalized assay: q_norm",
  "SpatialDecon raw assay: exprs",
  paste0(
    "SpatialDecon nuclei metadata column: ",
    nuclei_col
  ),
  "Figure 1G group order: Normal/Non-obese, Normal/Obese, Tumor/Non-obese, Tumor/Obese"
)

writeLines(
  summary_lines,
  con = file.path(
    OUTPUT_DIR,
    "Figure1G_SpatialDecon_summary.txt"
  )
)

writeLines(
  capture.output(
    sessionInfo()
  ),
  con = file.path(
    OUTPUT_DIR,
    "sessionInfo.txt"
  )
)

message("")
message("GeoMx SpatialDecon / Figure 1G completed.")
message(
  "Results written to: ",
  normalizePath(
    OUTPUT_DIR,
    mustWork = FALSE
  )
)
