#!/usr/bin/env Rscript

###############################################################################
# GeoMx DSP ssGSEA pathway analysis and Figure 1F
#
# Study:
#   Obesity-associated colorectal cancer spatial transcriptomics
#
# Purpose:
#   1. Load the preserved ROI-level ssGSEA score matrix.
#   2. Align ssGSEA samples with metadata from the preprocessed GeoMx object.
#   3. Calculate mean ssGSEA scores for the 12 ROI/Class/Obesity groups:
#
#        Adipose:    NO-, NO+, TO-, TO+
#        Immune:     NO-, NO+, TO-, TO+
#        Epithelial: NO-, NO+, TO-, TO+
#
#   4. Scale each pathway within each ROI type, as in the original Figure 1F
#      workflow.
#   5. Generate the five Figure 1F pathway heatmaps:
#
#        Oncogenesis
#        Progression
#        Adipo-Immune
#        Immune Remodeling
#        Metabolic Reprogramming
#
#   6. Export grouped ssGSEA scores and pathway-level statistical summaries.
#
# Required input:
#
#   1. Preprocessed GeoMx object generated by:
#        01_preprocessing_QC_normalization.R
#
#      default:
#        results/GeoMx/01_preprocessing_QC_normalization/
#          GeoMx_preprocessed_Q3_normalized.rds
#
#   2. Preserved ROI-level ssGSEA score matrix:
#        data/GeoMx/ssGSEA/ssgsea_results.csv
#
#      Rows    = pathways
#      Columns = GeoMx ROI/sample IDs
#
# Output:
#      results/GeoMx/03_ssGSEA_pathway_analysis/
#
###############################################################################


###############################################################################
# 0. Configuration
###############################################################################

PREPROCESSED_RDS <- Sys.getenv(
  "GEOMX_PREPROCESSED_RDS",
  unset = file.path(
    "results",
    "GeoMx",
    "01_preprocessing_QC_normalization",
    "GeoMx_preprocessed_Q3_normalized.rds"
  )
)

SSGSEA_RESULTS_FILE <- Sys.getenv(
  "GEOMX_SSGSEA_RESULTS",
  unset = file.path(
    "data",
    "GeoMx",
    "ssGSEA",
    "ssgsea_results.csv"
  )
)

OUTPUT_DIR <- Sys.getenv(
  "GEOMX_SSGSEA_OUTPUT_DIR",
  unset = file.path(
    "results",
    "GeoMx",
    "03_ssGSEA_pathway_analysis"
  )
)

dir.create(
  OUTPUT_DIR,
  recursive = TRUE,
  showWarnings = FALSE
)


###############################################################################
# 1. Required packages
###############################################################################

required_packages <- c(
  "Biobase",
  "dplyr",
  "tibble",
  "ComplexHeatmap",
  "circlize"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    logical(1),
    quietly = TRUE
  )
]

if (length(missing_packages) > 0) {
  stop(
    "Missing required package(s): ",
    paste(missing_packages, collapse = ", "),
    "\nInstall the required packages before running this script."
  )
}

suppressPackageStartupMessages({
  library(Biobase)
  library(dplyr)
  library(tibble)
  library(ComplexHeatmap)
  library(circlize)
})


###############################################################################
# 2. Helper functions
###############################################################################

clean_sample_id <- function(x) {
  
  x <- basename(
    as.character(x)
  )
  
  # remove .dcc extension
  x <- sub(
    "\\.dcc$",
    "",
    x,
    ignore.case = TRUE
  )
  
  # convert "-" to "."
  x <- gsub(
    "-",
    ".",
    x,
    fixed = TRUE
  )
  
  x
}


standardize_class <- function(x) {
  
  x <- trimws(
    as.character(x)
  )
  
  dplyr::case_when(
    tolower(x) == "normal" ~ "Normal",
    tolower(x) == "tumor"  ~ "Tumor",
    tolower(x) == "tumour" ~ "Tumor",
    TRUE ~ x
  )
}


standardize_obesity <- function(x) {
  
  x <- trimws(
    as.character(x)
  )
  
  low <- tolower(x)
  
  dplyr::case_when(
    low %in% c(
      "normal",
      "non-obese",
      "nonobese",
      "non obese",
      "non_obese"
    ) ~ "Normal",
    
    low == "obese" ~ "Obese",
    
    TRUE ~ x
  )
}


standardize_roi <- function(x) {
  
  x <- trimws(
    as.character(x)
  )
  
  dplyr::case_when(
    tolower(x) %in% c(
      "cd3",
      "immune",
      "immune cell"
    ) ~ "CD3",
    
    tolower(x) %in% c(
      "epithelial",
      "epithelium"
    ) ~ "Epithelial",
    
    tolower(x) %in% c(
      "adipose",
      "adipose tissue"
    ) ~ "Adipose",
    
    TRUE ~ x
  )
}


safe_row_zscore <- function(x) {
  
  s <- stats::sd(
    x,
    na.rm = TRUE
  )
  
  m <- mean(
    x,
    na.rm = TRUE
  )
  
  if (
    !is.finite(s) ||
    s == 0
  ) {
    return(
      rep(
        0,
        length(x)
      )
    )
  }
  
  (x - m) / s
}


safe_wilcox <- function(values, group) {
  
  ok <- (
    is.finite(values) &
      !is.na(group)
  )
  
  values <- values[ok]
  group <- droplevels(
    factor(group[ok])
  )
  
  if (
    length(values) == 0 ||
    nlevels(group) != 2
  ) {
    return(NA_real_)
  }
  
  tryCatch(
    stats::wilcox.test(
      values ~ group
    )$p.value,
    error = function(e) NA_real_
  )
}


###############################################################################
# 3. Load GeoMx metadata
###############################################################################

if (!file.exists(PREPROCESSED_RDS)) {
  stop(
    "Preprocessed GeoMx object was not found:\n",
    PREPROCESSED_RDS,
    "\nRun 01_preprocessing_QC_normalization.R first, or define ",
    "GEOMX_PREPROCESSED_RDS."
  )
}

target_geomx <- readRDS(
  PREPROCESSED_RDS
)

annotation <- as.data.frame(
  Biobase::pData(target_geomx),
  check.names = FALSE
)

required_metadata <- c(
  "ROIType",
  "class",
  "Category"
)

missing_metadata <- setdiff(
  required_metadata,
  colnames(annotation)
)

if (length(missing_metadata) > 0) {
  stop(
    "Required GeoMx metadata column(s) are missing: ",
    paste(
      missing_metadata,
      collapse = ", "
    )
  )
}

annotation$Sample <- clean_sample_id(
  rownames(annotation)
)

annotation$ROIType <- standardize_roi(
  annotation$ROIType
)

annotation$Class <- standardize_class(
  annotation$class
)

annotation$Obesity <- standardize_obesity(
  annotation$Category
)

annotation <- annotation |>
  dplyr::select(
    Sample,
    ROIType,
    Class,
    Obesity,
    dplyr::everything()
  )

rownames(annotation) <- annotation$Sample


###############################################################################
# 4. Load preserved ssGSEA score matrix
###############################################################################

if (!file.exists(SSGSEA_RESULTS_FILE)) {
  stop(
    "ssGSEA score matrix was not found:\n",
    SSGSEA_RESULTS_FILE,
    "\nPlace the preserved ssgsea_results.csv at the default location, ",
    "or define GEOMX_SSGSEA_RESULTS."
  )
}

ssgsea_results <- read.csv(
  SSGSEA_RESULTS_FILE,
  header = TRUE,
  row.names = 1,
  check.names = FALSE,
  stringsAsFactors = FALSE
)

ssgsea_results <- as.matrix(
  ssgsea_results
)

storage.mode(
  ssgsea_results
) <- "numeric"

colnames(
  ssgsea_results
) <- clean_sample_id(
  colnames(
    ssgsea_results
  )
)

if (
  anyDuplicated(
    colnames(
      ssgsea_results
    )
  )
) {
  stop(
    "Duplicate ssGSEA sample IDs were created after sample-ID standardization."
  )
}

common_samples <- intersect(
  rownames(annotation),
  colnames(ssgsea_results)
)

if (length(common_samples) == 0) {
  stop(
    "No common sample IDs were found between the GeoMx metadata and ",
    "the ssGSEA score matrix."
  )
}

if (
  length(common_samples) <
  ncol(ssgsea_results)
) {
  warning(
    ncol(ssgsea_results) -
      length(common_samples),
    " ssGSEA sample(s) were not matched to the GeoMx metadata."
  )
}

if (
  length(common_samples) <
  nrow(annotation)
) {
  warning(
    nrow(annotation) -
      length(common_samples),
    " GeoMx ROI(s) were not present in the ssGSEA score matrix."
  )
}

annotation <- annotation[
  common_samples,
  ,
  drop = FALSE
]

ssgsea_results <- ssgsea_results[
  ,
  common_samples,
  drop = FALSE
]

message(
  "Matched ssGSEA matrix: ",
  nrow(ssgsea_results),
  " pathways x ",
  ncol(ssgsea_results),
  " ROIs"
)


###############################################################################
# 5. Calculate group means
###############################################################################

# Final Figure 1F group order.
expected_groups <- c(
  "Adipose_Normal_Normal",
  "Adipose_Normal_Obese",
  "Adipose_Tumor_Normal",
  "Adipose_Tumor_Obese",
  
  "CD3_Normal_Normal",
  "CD3_Normal_Obese",
  "CD3_Tumor_Normal",
  "CD3_Tumor_Obese",
  
  "Epithelial_Normal_Normal",
  "Epithelial_Normal_Obese",
  "Epithelial_Tumor_Normal",
  "Epithelial_Tumor_Obese"
)

annotation$Group <- paste(
  annotation$ROIType,
  annotation$Class,
  annotation$Obesity,
  sep = "_"
)

unknown_groups <- setdiff(
  unique(annotation$Group),
  expected_groups
)

if (length(unknown_groups) > 0) {
  warning(
    "Unexpected ROI/Class/Obesity group(s) were found and are not used in ",
    "Figure 1F: ",
    paste(
      unknown_groups,
      collapse = ", "
    )
  )
}

group_counts <- table(
  factor(
    annotation$Group,
    levels = expected_groups
  )
)

group_count_df <- data.frame(
  Group = names(group_counts),
  N_ROIs = as.integer(group_counts),
  row.names = NULL
)

write.csv(
  group_count_df,
  file.path(
    OUTPUT_DIR,
    "Figure1F_group_ROI_counts.csv"
  ),
  row.names = FALSE
)

group_means <- matrix(
  NA_real_,
  nrow = nrow(ssgsea_results),
  ncol = length(expected_groups),
  dimnames = list(
    rownames(ssgsea_results),
    expected_groups
  )
)

for (g in expected_groups) {
  
  idx <- which(
    annotation$Group == g
  )
  
  if (length(idx) == 0) {
    next
  }
  
  group_means[, g] <- rowMeans(
    ssgsea_results[
      ,
      idx,
      drop = FALSE
    ],
    na.rm = TRUE
  )
}

# Short pathway names are used for Figure 1F, matching the original script.
short_pathway_names <- sub(
  "^[^-]*-",
  "",
  rownames(group_means)
)

if (anyDuplicated(short_pathway_names)) {
  duplicated_names <- unique(
    short_pathway_names[
      duplicated(short_pathway_names)
    ]
  )
  
  stop(
    "Pathway names become duplicated after removing category prefixes: ",
    paste(
      duplicated_names,
      collapse = ", "
    )
  )
}

rownames(group_means) <- short_pathway_names

write.csv(
  data.frame(
    Pathway = rownames(group_means),
    group_means,
    check.names = FALSE
  ),
  file.path(
    OUTPUT_DIR,
    "Figure1F_ssGSEA_group_means.csv"
  ),
  row.names = FALSE
)


###############################################################################
# 6. Define Figure 1F pathway groups
###############################################################################

pathway_groups <- list(
  
  Oncogenesis = c(
    "Wnt Signaling",
    "p53 Signaling",
    "Myc",
    "MET Signaling",
    "MAPK Signaling",
    "ERBB2 Signaling",
    "EGFR Signaling"
  ),
  
  Progression = c(
    "VEGF Signaling",
    "Purinergic Signaling",
    "Notch Signaling",
    "Hedgehog Signaling"
  ),
  
  Adipo_Immune = c(
    "PDGF Signaling",
    "Immune Exhaustion",
    "BCR Signaling"
  ),
  
  Immune_Remodeling = c(
    "Retinoic Acid Signaling",
    "Type II Interferon Signaling",
    "Type I Interferon Signaling",
    "Prostaglandin Inflammation",
    "Lymphocyte Trafficking",
    "Chemokine Signaling",
    "TCR Signaling"
  ),
  
  Metabolic_Reprogramming = c(
    "Pentose Phosphate",
    "Nucleotide Synthesis",
    "Lipid Metabolism",
    "Glutamine Metabolism",
    "Fatty Acid Synthesis"
  )
)

display_titles <- c(
  Oncogenesis = "Oncogenesis",
  Progression = "Progression",
  Adipo_Immune = "Adipo-Immune",
  Immune_Remodeling = "Immune Remodeling",
  Metabolic_Reprogramming = "Metabolic Reprogramming"
)

roi_blocks <- list(
  Adipose = expected_groups[1:4],
  Immune = expected_groups[5:8],
  Epithelial = expected_groups[9:12]
)

column_display_labels <- c(
  "NO\u207b",
  "NO\u207a",
  "TO\u207b",
  "TO\u207a"
)

heatmap_colors <- grDevices::colorRampPalette(
  c(
    "blue",
    "skyblue",
    "white",
    "salmon",
    "red"
  )
)(255)


###############################################################################
# 7. Figure 1F heatmaps
###############################################################################

scaled_matrices <- list()

for (group_name in names(pathway_groups)) {
  
  selected_pathways <- pathway_groups[[group_name]]
  
  missing_pathways <- setdiff(
    selected_pathways,
    rownames(group_means)
  )
  
  if (length(missing_pathways) > 0) {
    warning(
      "[",
      group_name,
      "] pathway(s) not found and omitted: ",
      paste(
        missing_pathways,
        collapse = ", "
      )
    )
  }
  
  selected_pathways <- intersect(
    selected_pathways,
    rownames(group_means)
  )
  
  if (length(selected_pathways) == 0) {
    warning(
      "[",
      group_name,
      "] no requested pathways were found; heatmap skipped."
    )
    next
  }
  
  # Preserve the explicit pathway order defined above.
  selected_pathways <- pathway_groups[[group_name]][
    pathway_groups[[group_name]] %in%
      selected_pathways
  ]
  
  selected_data <- group_means[
    selected_pathways,
    expected_groups,
    drop = FALSE
  ]
  
  selected_data_scaled <- matrix(
    NA_real_,
    nrow = nrow(selected_data),
    ncol = ncol(selected_data),
    dimnames = dimnames(selected_data)
  )
  
  # Original Figure 1F logic:
  # scale each pathway separately within each ROI type
  # across NO-, NO+, TO-, TO+.
  for (roi_name in names(roi_blocks)) {
    
    cols <- roi_blocks[[roi_name]]
    
    selected_data_scaled[
      ,
      cols
    ] <- t(
      apply(
        selected_data[
          ,
          cols,
          drop = FALSE
        ],
        1,
        safe_row_zscore
      )
    )
  }
  
  scaled_matrices[[group_name]] <- selected_data_scaled
  
  write.csv(
    data.frame(
      Pathway = rownames(selected_data_scaled),
      selected_data_scaled,
      check.names = FALSE
    ),
    file.path(
      OUTPUT_DIR,
      paste0(
        "Figure1F_",
        group_name,
        "_scaled_scores.csv"
      )
    ),
    row.names = FALSE
  )
  
  # A display copy with duplicated NO-/NO+/TO-/TO+ labels.
  heatmap_display <- selected_data_scaled
  
  colnames(
    heatmap_display
  ) <- rep(
    column_display_labels,
    times = 3
  )
  
  roi_split <- factor(
    rep(
      c(
        "Adipose ROI",
        "Immune ROI",
        "Epithelial ROI"
      ),
      each = 4
    ),
    levels = c(
      "Adipose ROI",
      "Immune ROI",
      "Epithelial ROI"
    )
  )
  
  ht <- ComplexHeatmap::Heatmap(
    heatmap_display,
    name = "ssGSEA\nscore",
    column_split = roi_split,
    column_gap = grid::unit(
      2.5,
      "mm"
    ),
    cluster_rows = FALSE,
    cluster_columns = FALSE,
    col = heatmap_colors,
    show_row_names = TRUE,
    show_column_names = TRUE,
    column_names_rot = 0,
    row_names_gp = grid::gpar(
      fontsize = 10
    ),
    column_names_gp = grid::gpar(
      fontsize = 9
    ),
    column_title_gp = grid::gpar(
      fontsize = 11,
      fontface = "bold"
    ),
    heatmap_legend_param = list(
      title = "ssGSEA\nscore",
      legend_height = grid::unit(
        28,
        "mm"
      )
    ),
    cell_fun = function(
    j,
    i,
    x,
    y,
    width,
    height,
    fill
    ) {
      grid::grid.rect(
        x = x,
        y = y,
        width = width,
        height = height,
        gp = grid::gpar(
          fill = fill,
          col = "black",
          lwd = 0.7
        )
      )
    }
  )
  
  # PDF
  grDevices::pdf(
    file.path(
      OUTPUT_DIR,
      paste0(
        "Figure1F_",
        group_name,
        ".pdf"
      )
    ),
    width = 8.0,
    height = max(
      3.0,
      0.45 * nrow(heatmap_display) + 2.0
    )
  )
  
  ComplexHeatmap::draw(
    ht,
    heatmap_legend_side = "right"
  )
  
  grid::grid.text(
    display_titles[[group_name]],
    x = 0.5,
    y = 0.985,
    just = c(
      "center",
      "top"
    ),
    gp = grid::gpar(
      fontsize = 14,
      fontface = "bold"
    )
  )
  
  grDevices::dev.off()
  
  # PNG
  grDevices::png(
    file.path(
      OUTPUT_DIR,
      paste0(
        "Figure1F_",
        group_name,
        ".png"
      )
    ),
    width = 8.0,
    height = max(
      3.0,
      0.45 * nrow(heatmap_display) + 2.0
    ),
    units = "in",
    res = 600
  )
  
  ComplexHeatmap::draw(
    ht,
    heatmap_legend_side = "right"
  )
  
  grid::grid.text(
    display_titles[[group_name]],
    x = 0.5,
    y = 0.985,
    just = c(
      "center",
      "top"
    ),
    gp = grid::gpar(
      fontsize = 14,
      fontface = "bold"
    )
  )
  
  grDevices::dev.off()
}


###############################################################################
# 8. Pathway-level statistical summaries
###############################################################################

# Use the original pathway names with category prefixes for statistics.
ssgsea_df <- as.data.frame(
  t(ssgsea_results),
  check.names = FALSE
)

ssgsea_df$Sample <- rownames(
  ssgsea_df
)

merged_df <- annotation |>
  dplyr::select(
    Sample,
    ROIType,
    Class,
    Obesity
  ) |>
  dplyr::left_join(
    tibble::rownames_to_column(
      as.data.frame(
        t(ssgsea_results),
        check.names = FALSE
      ),
      var = "Sample"
    ),
    by = "Sample"
  )

stat_categories <- list(
  
  Oncogenesis = list(
    ROIType = "Epithelial",
    Class = "Tumor",
    CompareBy = "Obesity",
    Pathways = c(
      "Signaling.Pathways-Wnt Signaling",
      "Signaling.Pathways-p53 Signaling",
      "Signaling.Pathways-Myc",
      "Signaling.Pathways-MET Signaling",
      "Signaling.Pathways-MAPK Signaling",
      "Signaling.Pathways-ERBB2 Signaling",
      "Signaling.Pathways-EGFR Signaling"
    )
  ),
  
  Progression = list(
    ROIType = "Epithelial",
    Class = NA_character_,
    CompareBy = "Class",
    Pathways = c(
      "Signaling.Pathways-VEGF Signaling",
      "Signaling.Pathways-Purinergic Signaling",
      "Signaling.Pathways-Notch Signaling",
      "Signaling.Pathways-Hedgehog Signaling"
    )
  ),
  
  Adipo_Immune = list(
    ROIType = "Adipose",
    Class = "Tumor",
    CompareBy = "Obesity",
    Pathways = c(
      "Signaling.Pathways-PDGF Signaling",
      "Immune.Response-Immune Exhaustion",
      "Adaptive.Immunity-BCR Signaling"
    )
  ),
  
  Immune_Remodeling = list(
    ROIType = "CD3",
    Class = "Tumor",
    CompareBy = "Obesity",
    Pathways = c(
      "Signaling.Pathways-Retinoic Acid Signaling",
      "Immune.Response-Type II Interferon Signaling",
      "Immune.Response-Type I Interferon Signaling",
      "Immune.Response-Prostaglandin Inflammation",
      "Immune.Response-Lymphocyte Trafficking",
      "Immune.Response-Chemokine Signaling",
      "Adaptive.Immunity-TCR Signaling"
    )
  ),
  
  Metabolic_Reprogramming = list(
    ROIType = "Epithelial",
    Class = "Tumor",
    CompareBy = "Obesity",
    Pathways = c(
      "Metabolism-Pentose Phosphate",
      "Metabolism-Nucleotide Synthesis",
      "Metabolism-Lipid Metabolism",
      "Metabolism-Glutamine Metabolism",
      "Metabolism-Fatty Acid Synthesis"
    )
  )
)

stat_results <- list()

result_index <- 1L

for (category_name in names(stat_categories)) {
  
  info <- stat_categories[[category_name]]
  
  df <- merged_df |>
    dplyr::filter(
      ROIType == info$ROIType
    )
  
  if (!is.na(info$Class)) {
    
    df <- df |>
      dplyr::filter(
        Class == info$Class
      )
  }
  
  for (pathway in info$Pathways) {
    
    if (!pathway %in% colnames(df)) {
      
      stat_results[[result_index]] <- data.frame(
        Category = category_name,
        Pathway = pathway,
        ROIType = info$ROIType,
        RestrictedClass = info$Class,
        Comparison = info$CompareBy,
        P_value = NA_real_,
        stringsAsFactors = FALSE
      )
      
      result_index <- result_index + 1L
      next
    }
    
    p <- safe_wilcox(
      df[[pathway]],
      df[[info$CompareBy]]
    )
    
    stat_results[[result_index]] <- data.frame(
      Category = category_name,
      Pathway = pathway,
      ROIType = info$ROIType,
      RestrictedClass = info$Class,
      Comparison = info$CompareBy,
      P_value = p,
      stringsAsFactors = FALSE
    )
    
    result_index <- result_index + 1L
  }
}

stat_results <- dplyr::bind_rows(
  stat_results
)

stat_results$P_adjust_BH <- stats::p.adjust(
  stat_results$P_value,
  method = "BH"
)

write.csv(
  stat_results,
  file.path(
    OUTPUT_DIR,
    "Figure1F_pathway_statistics.csv"
  ),
  row.names = FALSE
)


###############################################################################
# 9. Save analysis summary and software versions
###############################################################################

summary_lines <- c(
  paste0(
    "Input ssGSEA score file: ",
    SSGSEA_RESULTS_FILE
  ),
  paste0(
    "Matched ROIs: ",
    length(common_samples)
  ),
  paste0(
    "Pathways in score matrix: ",
    nrow(ssgsea_results)
  ),
  paste0(
    "Figure 1F pathway groups generated: ",
    length(scaled_matrices)
  ),
  "Group order within each ROI: NO-, NO+, TO-, TO+",
  "Scaling: pathway-wise z-score within each ROI type across the four groups",
  paste0(
    "Statistical summary tests: Wilcoxon rank-sum; BH-adjusted p-values also exported."
  ),
  "",
  "Important reproducibility note:",
  paste0(
    "The recovered study script starts from a precomputed ssgsea_results.csv. ",
    "The original obesity-specific gene-set definition and score-computation ",
    "script was not recovered and is therefore not reconstructed here."
  )
)

writeLines(
  summary_lines,
  con = file.path(
    OUTPUT_DIR,
    "Figure1F_ssGSEA_analysis_summary.txt"
  )
)

writeLines(
  capture.output(
    sessionInfo()
  ),
  con = file.path(
    OUTPUT_DIR,
    "sessionInfo.txt"
  )
)

message("")
message("GeoMx ssGSEA Figure 1F analysis completed.")
message(
  "Results written to: ",
  normalizePath(
    OUTPUT_DIR,
    mustWork = FALSE
  )
)
